swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: 1.0.0
  title: Swagger REST Article
consumes:
- application/json
produces:
- application/json

basePath: /

definitions:
  ElectricityReadings:
    type: array
    items:
      type: object
      properties:
        time:
          type: integer
        reading:
          type: number
  PricePlanComparisons:
    type: object
    properties:
      pricePlanId:
        type: string
      pricePlanComparisons:
        type: object
  PricePlanRecommendations:
    type: array
    items:
      type: object

# Paths supported by the server application
paths:
  /readings/store:
    post:
      operationId: controller.electricity_reading_controller.store
      tags:
      - Electricity Reading Controller
      summary: Store Readings
      parameters:
      - name: data
        in: body
        required: True
        schema:
          type: object
          properties:
            smartMeterId:
              type: string
            electricityReadings:
              $ref: '#/definitions/ElectricityReadings'
      responses:
        200:
          description: Successful store operation
          schema:
            type: object
            properties:
              smartMeterId:
                type: string
              electricityReadings:
                $ref: '#/definitions/ElectricityReadings'
  /readings/read/{smart_meter_id}:
    get:
      operationId: controller.electricity_reading_controller.read
      tags:
      - Electricity Reading Controller
      summary: Get Stored Readings
      parameters:
      - name: smart_meter_id
        in: path
        required: True
        description: A string value, e.g. smart-meter-0
        type: string
      responses:
        200:
          description: Successful read operation
          schema:
            $ref: '#/definitions/ElectricityReadings'
  /price-plans/compare-all/{smart_meter_id}:
    get:
      operationId: controller.price_plan_comparator_controller.compare
      tags:
      - Price Plan Comparator Controller
      summary: Compare prices for all plans for a given meter
      parameters:
      - name: smart_meter_id
        in: path
        required: True
        description: A string value, e.g. smart-meter-0
        type: string
      responses:
        200:
          description: Successful comparison operation
          schema:
            $ref: '#/definitions/PricePlanComparisons'
  /price-plans/recommend/{smart_meter_id}:
    get:
      operationId: controller.price_plan_comparator_controller.recommend
      tags:
      - Price Plan Comparator Controller
      summary: View recommended price plans for usage
      parameters:
      - name: smart_meter_id
        in: path
        required: True
        description: A string value, e.g. smart-meter-0
        type: string
      - in: query
        name: limit
        type: integer
        required: False
        description: Number of items to return        
      responses:
        200:
          description: Successful recommend operation
          schema:
            $ref: '#/definitions/PricePlanRecommendations'
